apiVersion: v1
kind: Service
metadata:
  name: library-service
  labels:
    run: library
spec:
  type: NodePort
  ports:
  - port: 8000
    nodePort: 30287
    protocol: TCP
  selector:
    app: library